project:
  type: book
  output-dir: docs
  
runtime: shiny

book:
  title: "Economie Générale II "
  author: "Pascaline Vincent"
  navbar: 
    search: true
    left: 
    - href: index.qmd
      text: Home
  sidebar:
    style: docked
    background: light
    logo: cover.jpg 
  search: true
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - plan_cours.qmd
    - chapitre_1.qmd
    - dossiers.qmd
    - references.qmd
bibliography: 
    - eco_generale.bib
citeproc: true


format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual
base-url: /eco_generale/
site-url: https://pasca20100.github.io/eco_generale/